package com.example.butigersandbloompos.theme

import androidx.compose.ui.graphics.Color

// Brand colors from the web app
val Brand = Color(0xFF1A6B4A)
val BrandLight = Color(0xFFE8F5EF)
val BrandHover = Color(0xFF155A3E)

// Light theme
val LightPrimary = Color(0xFF1A6B4A)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFB4F1D5)
val LightOnPrimaryContainer = Color(0xFF002113)
val LightSecondary = Color(0xFF4E6355)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD0E8D6)
val LightOnSecondaryContainer = Color(0xFF0B1F14)
val LightTertiary = Color(0xFF3C6472)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFBFE9F9)
val LightOnTertiaryContainer = Color(0xFF001F28)
val LightBackground = Color(0xFFF0F2F5)
val LightOnBackground = Color(0xFF1A1D23)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF1A1D23)
val LightSurfaceVariant = Color(0xFFDBE5DD)
val LightOnSurfaceVariant = Color(0xFF404943)
val LightOutline = Color(0xFFE5E7EB)
val LightError = Color(0xFFDC2626)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFEE2E2)

// Dark theme
val DarkPrimary = Color(0xFF98D5B9)
val DarkOnPrimary = Color(0xFF003824)
val DarkPrimaryContainer = Color(0xFF005236)
val DarkOnPrimaryContainer = Color(0xFFB4F1D5)
val DarkSecondary = Color(0xFFB5CCBB)
val DarkOnSecondary = Color(0xFF203529)
val DarkSecondaryContainer = Color(0xFF374B3E)
val DarkOnSecondaryContainer = Color(0xFFD0E8D6)
val DarkTertiary = Color(0xFFA4CDDD)
val DarkOnTertiary = Color(0xFF043542)
val DarkTertiaryContainer = Color(0xFF234C59)
val DarkOnTertiaryContainer = Color(0xFFBFE9F9)
val DarkBackground = Color(0xFF121418)
val DarkOnBackground = Color(0xFFE2E3E7)
val DarkSurface = Color(0xFF1A1C20)
val DarkOnSurface = Color(0xFFE2E3E7)
val DarkSurfaceVariant = Color(0xFF404943)
val DarkOnSurfaceVariant = Color(0xFFBFC9C1)
val DarkOutline = Color(0xFF3A3F3B)
val DarkError = Color(0xFFFF6B6B)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)

// Shared status colors
val Success = Color(0xFF16A34A)
val SuccessBg = Color(0xFFDCFCE7)
val Warning = Color(0xFFD97706)
val WarningBg = Color(0xFFFEF3C7)
val Danger = Color(0xFFDC2626)
val DangerBg = Color(0xFFFEE2E2)
